Repository BHoM/BHoM_Installer, pull requests merged in 2020-05, with the labels that each got.

#53 Include Psychrometrics_Toolkit
  include.txt
Labels: type:feature

#55 Add LadybugTools_Toolkit
  dependencies.txt
  include.txt
Labels: type:feature

#57 Add ReadMe
  README.md
Labels: type:documentation

#51 Add alternate configurations for Lusas_Toolkit builds
  altConfigs.txt
Labels: type:external-api-changes

#59 Add OpenStreetMap_Toolkit to installer
  include.txt
Labels: size:S
