Repository BHoM/BHoM_Installer, pull requests merged in 2020-11, with the labels that each got.

#103 Addition of File Toolkit
  include.txt
Labels: type:compliance

#105 Stop copying all DLLs to Dynamo/2.3/packages/BHoM/bin
  InstallerCore/Features.wxs
Labels: type:bug

#107 Maybe fix Dynamo?
  InstallerCore/Components.wxs
  InstallerCore/Directories.wxs
Labels: type:bug

#109 Add support for ETABS18
  altConfigs.txt
Labels: type:feature
