Repository BHoM/BHoM_Installer, pull requests merged in 2020-06, with the labels that each got.

#61 Fix Revit Addin Location
  InstallerCore/Components.wxs
Labels: severity:critical, type:bug

#63 Call PostBuild to generate upgrade json
  .gitignore
  InstallerCore/InstallerCore.wixproj
Labels: type:bug

#70 Uptick to 3.3 for new alpha installers
  BHoM_Installer/BHoM_Installer.wixproj
Labels: type:compliance
