Repository BHoM/BHoM_Installer, pull requests merged in 2024-01, with the labels that each got.

#213 Fix duplicate key error
  InstallerCore/Components.wxs
Labels: type:bug

#214 Update readme link
  README.md
Labels: type:documentation

#212 Add altConfig for Lusas210
  IncludedRepos/altConfigs.txt
Labels: type:feature
